### ISSUE TITLE
option of  inputting length of the required password usecase can be added to make the wordlist more accurate.

### ISSUE THREAD

**Issue by Codeboy12345** [edoardottt/longtongue#3]
when the user give the basic details such as name, surname etc. there must be an input option of setting the length of the password required each use time.
in this way the generated wordlist will be more accurate. 

also, somepeople use service/platform specific passwords (google, facebook, instagram, Pinterest)
so the password can also be generated like ('name''number''symbol''servicename')(ex:- codeboy123@facebook)

and some combination  like each letter of name merged with number such as ( c1o2d3e4b5o6y7) --> its just a name -'codeboy'  number after each letter 

it would be amazing if these features were added.

**Comment by edoardottt** [comment]
- I've added the possibility to set the minimum length for the passwords (`-m <int>`).

- For the second point, the service option like google, facebook and so on you can use the general keywords and the script will output also passwords similar to the one you are suggesting ('name''number''symbol''servicename')(ex:- codeboy123@facebook).

- For the third one I don't know if it could be useful because there are so many combinations you can create with numbers...so it would be useless to have millions and millions of passwords.
